/*
# `@mateothegreat/notion-sync` API Playbook

> See [httpyac/examples/](https://github.com/httpyac/httpyac.github.io/tree/main/examples) for examples of things you can do with `httpyac`.

*/
@baseUrl = https://api.notion.com/v1
@notionApiKey = {{token}}
@pageId = 1ded7342-e571-802e-8d06-fca37dbe8bc4
@propertyId = %3DIr%5C

{{+
  exports.notionHeaders = {
    'Content-Type': 'application/json',
    'Authorization': `Bearer {{token}}`,
    'Notion-Version': '2022-06-28'
  };
}}
{{
  console.log("hook that runs before every request");
}}
# @name getPage
# @title Get a page
# @injectVariables
# @trace

GET {{baseUrl}}/pages/{{pageId}}
...notionHeaders
>>! ./get-page.json
{{
  const { equal } = require('assert');
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
  test('object is page', () => {
    equal(response.parsedBody.object, 'page');
  });
}}


HTTP/1.1 200  - OK
date: Mon, 07 Jul 2025 07:11:54 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
connection: close
cf-ray: 95b587cdaf403ab9-DFW
cf-cache-status: DYNAMIC
content-encoding: gzip
etag: W/"11aa-kTfon221SoVzd6sAmtf9eGeTpFE"
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
content-security-policy: default-src 'none'
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-dns-prefetch-control: off
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-notion-request-id: 3402b76f-d198-4f4a-aea1-57721d8720c7
x-permitted-cross-domain-policies: none
x-xss-protection: 0
server: cloudflare
alt-svc: h3=":443"; ma=86400